global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mooder-backend
    metrics_path: /q/metrics
    static_configs:
      - targets: ["backend:8080"]
        labels:
          service: backend
          env: local
